<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.shoppingCart</groupId>
  <artifactId>commerce-craft</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
    <module>commerce-craft-core</module>
    <module>commerce-craft-infrastructure</module>
    <module>commerce-craft-api</module>
    <module>commerce-craft-bom</module>
    <module>commerce-craft-starter</module>
  </modules>

</project>
